# Uncomment the next line to define a global platform for your project
platform :osx, '11.0'

target 'Bagel' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  use_frameworks!

  pod 'CocoaAsyncSocket', '~> 7.6.5'
  pod 'macOSThemeKit', '~> 1.2.0'
  pod 'Highlightr'
  pod 'PeerTalk', '~> 0.1.0'
  
end
